
version: 2.1

docker_image: &docker_image
  image: cimg/base:stable
commands:
  print_pipeline_id:
    description: "Print the pipeline ID"
    steps:
      - run:
          name: "Print the pipeline ID"
          command: "echo -e 'Workflow ID: $CIRCLE_WORKFLOW_ID \nIt works!'"
jobs:
  build:
    docker:
      - <<: *docker_image
    steps:
      - print_pipeline_id
workflows:
  workflow-id:
    jobs:
      - build
