
version: 2.1
commands:
  print_pipeline_id:
    description: "Print the pipeline ID"
    steps:
      - run:
          name: "Print the pipeline ID"
          command: "echo Workflow ID: $CIRCLE_WORKFLOW_ID"
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: print_pipeline_id
workflows:
  workflow-id:
    jobs:
      - build
