
version: 2.1

docker_image: &docker_image
  image: cimg/base:stable
commands:
  fail-on-purpose:
    description: "This command will fail on purpose"
    steps:
      - run:
          name: "Return 1"
          command: "exit 1"
jobs:
  fail:
    docker:
      - <<: *docker_image
    steps:
      - fail-on-purpose
  run-on-failure:
    docker:
      - <<: *docker_image
    steps:
      - run:
          name: "Run on failure"
          command: "echo run on failure"
          when: on_fail
workflows:
  workflow-id:
    jobs:
      - build
